#!/bin/bash
# Launch the cursesDemo.py in a custom xterm window (via cursesDemoLauncher.py
# which allows catching SyntaxError's)

DEBUG=0  # If the window crashes immediately set this

if [ -f cursesDemoLauncher.py ] ; then
  LAUNCHER=cursesDemoLauncher.py
elif [ -f demos/cursesDemoLauncher.py ] ; then
  LAUNCHER=demos/cursesDemoLauncher.py
else
  echo "$0: Could not find cursesDemoLauncher.py"
  exit
fi

if [ $DEBUG -eq 0 ] ; then
  HOLD=+hold
else
  HOLD=-hold
fi

xterm $HOLD +sb +aw -geometry 165x45 -bg black -fg green +ah +bc +ls -cr yellow +uc \
  -T "Term Cube" \
  -xrm "XTerm*vt100.pointerShape:           left_ptr" \
  -xrm "XTerm*vt100.pointerColor:           green" \
  -xrm "XTerm*vt100.pointerColorBackground: black" \
  -e python $LAUNCHER xterm &

# +hold                  # Immediately destroy
# +sb                    # No scrollbar
# +aw                    # No autowrap
# -geometry 165x45       # Window (Host on RFTD is 166x50 max)
# -bg black              # Back
# -fg green              # Front
# +ah                    # Highlighting based on focus
# +bc                    # No cursor blinking
# +ls                    # Not login shell
# -cr yellow             # Text cursor
# +uc                    # Cursor is a box
# -T Term_Cube           # Title
# -xrm ...               # Resource string
#      pointerShape      # crosshair, left_ptr, xterm, top_left_arrow
# -e ./displayControl.py # Run

